string=input("type something")
string=string.replace("!"," ")
string=string.replace(","," ")
string=string.replace("."," ")
string=string.replace("''"," ")
string=string.replace("?"," ")
string=string.replace(";"," ")
string=string.replace("-"," ")
string=string.replace("'"," ")
print(string)

